# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x0breplication\"(\n\x12\x41ppendEntryRequest\x12\x12\n\nentry_json\x18\x01 \x01(\t\"&\n\x13\x41ppendEntryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"8\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\"9\n\x13RequestVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\"K\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t2\xb8\x01\n\x12ReplicationService\x12P\n\x0b\x41ppendEntry\x12\x1f.replication.AppendEntryRequest\x1a .replication.AppendEntryResponse\x12P\n\x0bRequestVote\x12\x1f.replication.RequestVoteRequest\x1a .replication.RequestVoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPENDENTRYREQUEST']._serialized_start=34
  _globals['_APPENDENTRYREQUEST']._serialized_end=74
  _globals['_APPENDENTRYRESPONSE']._serialized_start=76
  _globals['_APPENDENTRYRESPONSE']._serialized_end=114
  _globals['_REQUESTVOTEREQUEST']._serialized_start=116
  _globals['_REQUESTVOTEREQUEST']._serialized_end=172
  _globals['_REQUESTVOTERESPONSE']._serialized_start=174
  _globals['_REQUESTVOTERESPONSE']._serialized_end=231
  _globals['_SENDMESSAGERESPONSE']._serialized_start=233
  _globals['_SENDMESSAGERESPONSE']._serialized_end=308
  _globals['_REPLICATIONSERVICE']._serialized_start=311
  _globals['_REPLICATIONSERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
